/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Complejo;
import javax.swing.JOptionPane;

/**
 *
 * @author sony
 */
public class Principal3 extends javax.swing.JFrame {

    /**
     * Creates new form Principal3
     */
    public Principal3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtReal1 = new javax.swing.JTextField();
        txtImaginario1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbOperaciones = new javax.swing.JComboBox<>();
        txtReal2 = new javax.swing.JTextField();
        txtImaginario2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtReal3 = new javax.swing.JTextField();
        txtImaginario3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmdLimpiar = new javax.swing.JButton();
        cmdCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 3, 24)); // NOI18N
        jLabel1.setText("Operaciones con Numeros Complejos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 420, -1));

        txtReal1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtReal1KeyTyped(evt);
            }
        });
        jPanel1.add(txtReal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 40, 30));

        txtImaginario1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImaginario1KeyTyped(evt);
            }
        });
        jPanel1.add(txtImaginario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 40, 30));

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel2.setText("i");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 10, 30));

        cmbOperaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suma", "Resta", "Multiplicacion", "Division" }));
        jPanel1.add(cmbOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        txtReal2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtReal2KeyTyped(evt);
            }
        });
        jPanel1.add(txtReal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 40, 30));

        txtImaginario2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImaginario2KeyTyped(evt);
            }
        });
        jPanel1.add(txtImaginario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 40, 30));

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel3.setText("i");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 10, 30));

        jLabel4.setText("Resultado =");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        txtReal3.setEditable(false);
        jPanel1.add(txtReal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 40, 30));

        txtImaginario3.setEditable(false);
        jPanel1.add(txtImaginario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 40, 30));

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel5.setText("i");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 10, 30));

        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 70, -1));

        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
        int op, r1, r2, i1, i2;
        Complejo c1, c2, c3 = null;

        if (txtReal1.getText().isEmpty()) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Digite El Numero Real 1", "Error", JOptionPane.ERROR_MESSAGE);
            txtReal1.requestFocusInWindow();
        } else if (txtImaginario1.getText().isEmpty()) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Digite El Numero Imaginario 1", "Error", JOptionPane.ERROR_MESSAGE);
            txtImaginario1.requestFocusInWindow();
        } else if (txtReal2.getText().isEmpty()) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Digite El Numero Real 2", "Error", JOptionPane.ERROR_MESSAGE);
            txtReal2.requestFocusInWindow();
        } else if (txtImaginario2.getText().isEmpty()) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Digite El Numero Imaginario 2", "Error", JOptionPane.ERROR_MESSAGE);
            txtImaginario2.requestFocusInWindow();
        } else {

            op = cmbOperaciones.getSelectedIndex();

            r1 = Integer.parseInt((txtReal1).getText());
            r2 = Integer.parseInt((txtReal2).getText());
            i1 = Integer.parseInt((txtImaginario1).getText());
            i2 = Integer.parseInt((txtImaginario2).getText());

            c1 = new Complejo(r1, i1);
            c2 = new Complejo(r2, i2);

            switch (op) {
                case 0:
                    c3 = c1.sumar(c2);

                    break;

                case 1:
                    c3 = c1.restar(c2);
                    break;

                case 2:
                    c3 = c1.multiplicar(c2);
                    break;

                case 3:
                    c3 = c1.dividir(c2);
                    break;

            }
            txtImaginario3.setText("" + c3.getImaginario());
            txtReal3.setText("" + c3.getReal());
        }
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
    txtImaginario1.setText("");
    txtImaginario2.setText("");
    txtImaginario3.setText("");
    txtReal1.setText("");
    txtReal2.setText("");
    txtReal3.setText("");
    txtReal1.requestFocusInWindow();
        
        
        
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void txtReal1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReal1KeyTyped
     char c=evt.getKeyChar();
          if(!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar()!='-'){ 
              getToolkit().beep(); 
              evt.consume(); 
          }
    }//GEN-LAST:event_txtReal1KeyTyped

    private void txtImaginario1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImaginario1KeyTyped
    char c=evt.getKeyChar();
          if(!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar()!='-'){ 
              getToolkit().beep(); 
              evt.consume(); 
          }
    }//GEN-LAST:event_txtImaginario1KeyTyped

    private void txtReal2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReal2KeyTyped
    char c=evt.getKeyChar();
          if(!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar()!='-'){ 
              getToolkit().beep(); 
              evt.consume(); 
          }
    }//GEN-LAST:event_txtReal2KeyTyped

    private void txtImaginario2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImaginario2KeyTyped
    char c=evt.getKeyChar();
          if(!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar()!='-'){ 
              getToolkit().beep(); 
              evt.consume(); 
          }
    }//GEN-LAST:event_txtImaginario2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOperaciones;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtImaginario1;
    private javax.swing.JTextField txtImaginario2;
    private javax.swing.JTextField txtImaginario3;
    private javax.swing.JTextField txtReal1;
    private javax.swing.JTextField txtReal2;
    private javax.swing.JTextField txtReal3;
    // End of variables declaration//GEN-END:variables
}
